<?php

/**
 * @file
 * Contains viewsreference_filter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function viewsreference_filter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the viewsreference_filter module.
    case 'help.page.viewsreference_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Expose filters for editors to configure views') . '</p>';
      return $output;

    default:
  }
}
